// Icon registry (Lucide, ISC). Import icons here only, so bundles stay tree-shaken
// and the whole product draws from one consistent, rounded 2px-stroke set.

import { raw, type RawHTML } from './html';
import {
  Activity,
  ArrowLeft,
  ArrowRight,
  ArrowUpRight,
  Ban,
  Bell,
  Calendar,
  CalendarClock,
  ChartColumn,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  CircleAlert,
  CircleCheck,
  Clipboard,
  Clock,
  Code,
  Coffee,
  Copy,
  CornerDownRight,
  Crown,
  Download,
  ExternalLink,
  Eye,
  EyeOff,
  FileSpreadsheet,
  FileText,
  FileUp,
  Globe,
  Hash,
  HelpCircle,
  House,
  Image,
  ImageOff,
  Info,
  KeyRound,
  Languages,
  LayoutGrid,
  LineChart,
  Link,
  Link2,
  Link2Off,
  List,
  Lock,
  LogOut,
  Mail,
  MailOpen,
  MapPin,
  Megaphone,
  Menu,
  MessageCircle,
  Monitor,
  MoreHorizontal,
  MousePointerClick,
  Palette,
  Pencil,
  Plus,
  QrCode,
  Radio,
  RefreshCw,
  Rocket,
  Route,
  Search,
  Send,
  Settings,
  Share2,
  Shield,
  Smartphone,
  Sparkle,
  Split,
  Tag,
  Tags,
  Target,
  Terminal,
  Timer,
  Trash2,
  TrendingUp,
  TriangleAlert,
  Upload,
  User,
  Users,
  WandSparkles,
  X,
  Zap,
} from 'lucide-static';

const ICONS = {
  activity: Activity,
  'arrow-left': ArrowLeft,
  'arrow-right': ArrowRight,
  'arrow-up-right': ArrowUpRight,
  ban: Ban,
  bell: Bell,
  calendar: Calendar,
  'calendar-clock': CalendarClock,
  chart: ChartColumn,
  check: Check,
  'chevron-down': ChevronDown,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'circle-alert': CircleAlert,
  'circle-check': CircleCheck,
  clipboard: Clipboard,
  clock: Clock,
  code: Code,
  coffee: Coffee,
  copy: Copy,
  'corner-down-right': CornerDownRight,
  crown: Crown,
  download: Download,
  'external-link': ExternalLink,
  eye: Eye,
  'eye-off': EyeOff,
  'file-spreadsheet': FileSpreadsheet,
  'file-text': FileText,
  'file-up': FileUp,
  globe: Globe,
  hash: Hash,
  help: HelpCircle,
  house: House,
  image: Image,
  'image-off': ImageOff,
  info: Info,
  key: KeyRound,
  languages: Languages,
  grid: LayoutGrid,
  'line-chart': LineChart,
  link: Link,
  'link-2': Link2,
  'link-off': Link2Off,
  list: List,
  lock: Lock,
  'log-out': LogOut,
  mail: Mail,
  'mail-open': MailOpen,
  'map-pin': MapPin,
  megaphone: Megaphone,
  menu: Menu,
  message: MessageCircle,
  monitor: Monitor,
  more: MoreHorizontal,
  click: MousePointerClick,
  palette: Palette,
  pencil: Pencil,
  plus: Plus,
  qr: QrCode,
  radio: Radio,
  refresh: RefreshCw,
  rocket: Rocket,
  route: Route,
  search: Search,
  send: Send,
  settings: Settings,
  share: Share2,
  shield: Shield,
  smartphone: Smartphone,
  sparkle: Sparkle,
  split: Split,
  tag: Tag,
  tags: Tags,
  target: Target,
  terminal: Terminal,
  timer: Timer,
  trash: Trash2,
  trending: TrendingUp,
  warning: TriangleAlert,
  upload: Upload,
  user: User,
  users: Users,
  wand: WandSparkles,
  x: X,
  zap: Zap,
} as const;

export type IconName = keyof typeof ICONS;

export const ICON_NAMES = Object.keys(ICONS) as IconName[];

const cache = new Map<string, string>();

/**
 * SVG markup for an icon. Sized by CSS (defaults to 1em square) and hidden from
 * assistive tech — pair icon-only buttons with aria-label.
 */
export function iconSvg(name: IconName, className = 'size-4', strokeWidth = 2): string {
  const key = `${name}|${className}|${strokeWidth}`;
  const hit = cache.get(key);
  if (hit) return hit;
  const svg = ICONS[name]
    .trim()
    .replace(/\s*\n\s*/g, ' ')
    .replace(/class="[^"]*"/, `class="${className}"`)
    .replace(/ width="24"/, '')
    .replace(/ height="24"/, '')
    .replace(/stroke-width="2"/, `stroke-width="${strokeWidth}"`)
    .replace('<svg', '<svg aria-hidden="true" focusable="false"');
  cache.set(key, svg);
  return svg;
}

/** Icon for use inside `html` templates. */
export function icon(name: IconName, className = 'size-4', strokeWidth = 2): RawHTML {
  return raw(iconSvg(name, className, strokeWidth));
}
